name: CI/CD Pipeline for Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwrighttests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.47.2-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Playwright Browsers (including Chrome)
      run: |
        npx playwright install --with-deps chrome  # Install necessary Playwright browsers including Chrome

    - name: Install dependencies
      run: npm ci

    - name: Start application
      run: |
        chmod +x ./shopping-store-linux-amd64
        ./shopping-store-linux-amd64 &
      timeout-minutes: 2
      env:
        NODE_ENV: production

    - name: Run Playwright tests
      run: npx playwright test --timeout=60000  # Run the tests in headless mode

    - name: Generate Playwright report
      run: npx playwright show-report

    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report

    - name: Upload Test Results (JUnit)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.xml

    - name: Clean up
      if: always()
      run: |
        jobs=$(jobs -p)
        if [ -n "$jobs" ]; then
          kill $jobs
        else
          echo "No background processes to clean up"
        fi
        echo "Cleanup complete"
