name: CI/CD Pipeline for Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwrighttests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.47.2-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        HOME: /root  # This will fix the issue with Firefox

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install wait-on
      run: npm install wait-on --save-dev  # Ensures wait-on is installed

    - name: Start application
      run: |
        chmod +x ./shopping-store-linux-amd64
        ./shopping-store-linux-amd64 &
      timeout-minutes: 3  # Increased to 3 minutes
      env:
        NODE_ENV: production

    - name: Wait for server to start
      run: npx wait-on http://localhost:2221

    - name: Check server health
      run: curl -f http://localhost:2221/health || exit 1

    - name: Run Playwright tests
      run: npx playwright test --timeout=60000

    - name: Generate Playwright report
      run: npx playwright show-report

    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report

    - name: Fix permissions for results.xml
      run: sudo chmod 777 results.xml

    - name: Upload Test Results (JUnit)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results.xml

    - name: Clean up
      if: always()
      run: |
        jobs=$(jobs -p)
        if [ -n "$jobs" ]; then
          kill $jobs || echo "No background processes to kill"
        fi
        echo "Cleanup complete"
